blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/developtheweb/meowchi/discussions
    about: Please ask and answer questions here
  - name: Security Issues
    url: mailto:developtheweb@protonmail.com
    about: Please report security vulnerabilities via email